"""empty message

Revision ID: 06821715fa44
Revises: 2e97c127fe9d
Create Date: 2023-06-25 21:27:41.765226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06821715fa44'
down_revision = '2e97c127fe9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
