"""empty message

Revision ID: 2e97c127fe9d
Revises: 7eee013f03dd
Create Date: 2023-06-25 21:27:08.049096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e97c127fe9d'
down_revision = '7eee013f03dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
