"""empty message

Revision ID: b2312143eb05
Revises: 06821715fa44
Create Date: 2023-06-25 21:28:21.846170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2312143eb05'
down_revision = '06821715fa44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('storefilename', sa.Text(), nullable=False))
    op.drop_column('result', 'store_filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('store_filename', sa.INTEGER(), nullable=False))
    op.drop_column('result', 'storefilename')
    # ### end Alembic commands ###
