"""empty message

Revision ID: c797b86c69f7
Revises: d3ff5daecba4
Create Date: 2023-06-25 21:25:55.751556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c797b86c69f7'
down_revision = 'd3ff5daecba4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('storeFilename', sa.Integer(), nullable=False))
    op.drop_column('result', 'malwarefile_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('malwarefile_id', sa.INTEGER(), nullable=False))
    op.drop_column('result', 'storeFilename')
    # ### end Alembic commands ###
