"""empty message

Revision ID: eb75042a0121
Revises: b2312143eb05
Create Date: 2023-06-25 21:28:58.497165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb75042a0121'
down_revision = 'b2312143eb05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('store_filename', sa.Text(), nullable=False))
    op.drop_column('result', 'storefilename')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('storefilename', sa.TEXT(), nullable=False))
    op.drop_column('result', 'store_filename')
    # ### end Alembic commands ###
